# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 112d32d56bfbd431cafcc96f095ff5c66be429ad40a8be95ab5a955c6aeae37180c5c5eefd70ed0aa75ef853b1437826b38b1d4d979da8a8845dcdc5673af4fd

test:
  secret_key_base: 47bca503683cabad671fa332b625eb92ba2d60ffd7cdd9da0a3246fa0f788bd776f2662d6acee035cc12d0298f83a81f23bd14b45299931303f8ed6658add1ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
